version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "playing-py"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-78ak9jxzhfl7"
s3_prefix = "playing-py"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
